[package]
name = "qipice"
version = "0.1.0"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
description = "An ICE example"
repository = "https://github.com/Renmusxd/RustQIP"
license = "MIT"
edition = "2018"

[lib]
name = "qip"

[dependencies]
num = "^0.4"